Repository textlint/textlint, pull requests merged in 2023-01, with the labels that each got.

#984 refactor: update to structured-source@4
  packages/@textlint/kernel/package.json
  packages/@textlint/kernel/src/context/TextlintSourceCodeImpl.ts
  packages/textlint/package.json
  yarn.lock
Labels: Type: Refactoring, dependencies

#990 refactor(kernel): replace assert with invariant function
  packages/@textlint/kernel/src/context/TextlintFilterRuleContextImpl.ts
  packages/@textlint/kernel/src/context/TextlintRuleContextFixCommandGeneratorImpl.ts
  packages/@textlint/kernel/src/context/TextlintRuleContextImpl.ts
  packages/@textlint/kernel/src/context/TextlintSourceCodeImpl.ts
  packages/@textlint/kernel/src/core/source-location.ts
  packages/@textlint/kernel/src/fixer/fixer-processor.ts
  packages/@textlint/kernel/src/fixer/rule-fixer.ts
  packages/@textlint/kernel/src/linter/linter-processor.ts
  packages/@textlint/kernel/src/task/textlint-core-task.ts
  packages/@textlint/kernel/src/textlint-kernel.ts
  packages/@textlint/kernel/src/util/invariant.ts
Labels: Type: Refactoring

#1000 CI: add release script
  .github/release.yml
  .github/workflows/create-release-pr.yml
  .github/workflows/release.yml
  docs/CONTRIBUTING.md
Labels: Type: Release, Type: CI

#1008 feat(ast-node-types): Add individual Node type and Add Table/TableRow/TableCell node
  docs/txtnode.md
  packages/@textlint/ast-node-types/src/ASTNodeTypes.ts
  packages/@textlint/ast-node-types/src/NodeType.ts
  packages/@textlint/ast-node-types/src/TypeofTxtNode.ts
  packages/@textlint/ast-node-types/src/index.ts
  packages/@textlint/types/test/Rule/TextlintRuleModule-test.ts
  packages/@textlint/types/test/Rule/TxtNode-test.ts
Labels: Type: Feature, Type: Breaking Change, Type: Typescript

#1011 refactor(textlint): use New CLI by default
  README.md
  docs/use-as-modules.md
  packages/@textlint/kernel/src/textlint-kernel.ts
  packages/textlint/bin/textlint-esm.js
  packages/textlint/bin/textlint.js
  packages/textlint/package.json
  packages/textlint/src/cli-new.ts
  packages/textlint/src/cli.ts
  packages/textlint/test/cli-new/cli-test.ts
  packages/textlint/test/cli-new/fixtures/.textlintrc.json
  packages/textlint/test/cli-new/fixtures/fixer-rules/fixer-rule-add.ts
  packages/textlint/test/cli-new/fixtures/fixer-rules/fixer-rule-remove.ts
  packages/textlint/test/cli-new/fixtures/fixer-rules/fixer-rule-replace.ts
  packages/textlint/test/cli-new/fixtures/fixer-rules/input.md
  packages/textlint/test/cli-new/fixtures/fixer-rules/output.md
  packages/textlint/test/cli-new/fixtures/pass.html
  packages/textlint/test/cli-new/fixtures/quite.textlintrc.json
  packages/textlint/test/cli-new/fixtures/rules/@textlint/textlint-rule-example.ts
  packages/textlint/test/cli-new/fixtures/rules/async-rule.ts
  packages/textlint/test/cli-new/fixtures/rules/example-rule.ts
  packages/textlint/test/cli-new/fixtures/rules/issue81/no-default-assign-rule.ts
  packages/textlint/test/cli-new/fixtures/rules/no-error/textlint-rule-no-error.ts
  packages/textlint/test/cli-new/fixtures/rules/no-todo.ts
  packages/textlint/test/cli-new/fixtures/test.md
  packages/textlint/test/cli-new/fixtures/todo.html
  packages/textlint/test/cli-new/fixtures/todo.md
  packages/textlint/test/cli/cli-test.ts
Labels: Type: Breaking Change

#1013 fix(textlint): textlint --init create .textlintrc.json
  packages/textlint/src/config/config-initializer.ts
  packages/textlint/test/config-initializer/config-initializer-test.ts
Labels: Type: Bug, Type: Breaking Change

#1014 chore: Change "target" to "ES2018"
  tsconfig.base.json
Labels: Type: Breaking Change

#1019 refactor: add textlint-script/example* to workspaces
  package.json
  packages/textlint-scripts/example-ts/package.json
  packages/textlint-scripts/example-ts/src/module.ts
  packages/textlint-scripts/example-ts/test/index-test.ts
  packages/textlint-scripts/example-ts/tsconfig.json
  packages/textlint-scripts/example/package.json
  packages/textlint-tester/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: Type: Refactoring

#1020 refactor: use npm 9+ instead of yarn v1
  .github/ISSUE_TEMPLATE.md
  .github/workflows/ci.yml
  .github/workflows/create-release-pr.yml
  .github/workflows/release.yml
  .github/workflows/website.yml
  docs/CONTRIBUTING.md
  examples/use-as-ts-module/README.md
  lerna.json
  netlify.toml
  nx.json
  package-lock.json
  package.json
  test/integration-test/README.md
  test/integration-test/run_lint.js
  website/package.json
  yarn.lock
Labels: Type: Refactoring

#1022 fix(ast-node-types): export { TxtNodeRange, TxtNodeLocation, TxtNodePosition }
  docs/txtnode.md
  packages/@textlint/ast-node-types/src/NodeType.ts
  packages/@textlint/ast-node-types/src/index.ts
Labels: Type: Bug, Type: Typescript

#1024 fix(ast-node-types): export { TxtNodeType }
  packages/@textlint/ast-node-types/src/index.ts
Labels: Type: Bug, Type: Typescript

#1027 refactor(kernel): use fast-equals instead of deep-equal
  package-lock.json
  packages/@textlint/config-loader/package.json
  packages/@textlint/kernel/package.json
  packages/@textlint/kernel/src/descriptor/TextlintFilterRuleDescriptor.ts
  packages/@textlint/kernel/src/descriptor/TextlintLintableRuleDescriptor.ts
  packages/@textlint/kernel/src/descriptor/TextlintPluginDescriptor.ts
  packages/@textlint/kernel/test/descriptor/TextlintPluginDescritors-test.ts
  packages/@textlint/source-code-fixer/package.json
  packages/textlint/package.json
Labels: Type: Refactoring

#1031 chore(deps): update to rc-config-loader@4
  package-lock.json
  packages/textlint/package.json
Labels: Type: Dependencies

#1033 fix(ast-node-types): remove markdown extension && fix TxtNodeType
  packages/@textlint/ast-node-types/src/NodeType.ts
  packages/@textlint/kernel/src/context/TextlintRuleContextImpl.ts
  packages/@textlint/kernel/test/helper/BinaryPlugin.ts
  packages/@textlint/kernel/test/source-location/source-location-test.ts
  packages/@textlint/markdown-to-ast/src/index.ts
  packages/@textlint/markdown-to-ast/src/mapping/markdown-syntax-map.ts
  packages/@textlint/text-to-ast/src/plaintext-syntax.ts
  packages/@textlint/types/src/Rule/TextlintRuleContext.ts
  packages/@textlint/types/src/Rule/TextlintRuleModule.ts
  packages/textlint/test/cli/fixtures/fixer-rules/fixer-rule-add.ts
  packages/textlint/test/rule-context/rule-context-test.ts
Labels: Type: Bug, Type: Typescript

#1035 fix(ast-node-type): fix Node → TxtNode
  packages/@textlint/ast-node-types/src/NodeType.ts
  packages/@textlint/ast-node-types/tsconfig.json
  packages/@textlint/types/tsconfig.json
Labels: Type: Bug

#1043 test(textlint): remove it.only and use ts-node/esm
  package-lock.json
  packages/textlint/.mocharc.json
  packages/textlint/package.json
  packages/textlint/test/textlint-core/textlint-core-test.ts
  packages/textlint/test/tsconfig.json
  packages/textlint/tsconfig.json
Labels: Type: Testing
