Repository textlint/textlint, pull requests merged in 2023-02, with the labels that each got.

#1050 test(textlint): add test for CLI
  packages/textlint/test/cli/cli-test.ts
  packages/textlint/test/cli/fixtures/fixer-rules/input.md
  packages/textlint/test/cli/fixtures/fixer-rules/output.md
Labels: Type: Testing

#1052 textlint: improve debug log
  packages/@textlint/kernel/src/textlint-kernel.ts
  packages/textlint/src/cli.ts
  packages/textlint/src/createLinter.ts
  website/.textlintrc
Labels: Type: Refactoring

#1062 fix(kernel): Descriptor#toJSON should return normalized option
  packages/@textlint/kernel/src/descriptor/TextlintFilterRuleDescriptor.ts
  packages/@textlint/kernel/src/descriptor/TextlintLintableRuleDescriptor.ts
  packages/@textlint/kernel/src/descriptor/TextlintPluginDescriptor.ts
  packages/@textlint/kernel/src/descriptor/TextlintRuleDescriptors.ts
  packages/@textlint/kernel/test/descriptor/TextlintKernelDescriptor-test.ts
  packages/@textlint/kernel/test/snapshots/plugin-parse-error-should-be-lint-messages/output.json
  packages/textlint/test/cli/cli-test.ts
Labels: Type: Bug

#1067 feat(textlint-tester): add description field
  packages/textlint-tester/README.md
  packages/textlint-tester/src/test-util.ts
  packages/textlint-tester/src/textlint-tester.ts
  packages/textlint-tester/test/textlint-tester-error-format.ts
Labels: Type: Feature

#1074 feat(config-loader): add `type` and `ruleKey` to config descriptor
  packages/@textlint/config-loader/src/TextlintConfigDescriptor.ts
  packages/@textlint/config-loader/src/loader.ts
  packages/@textlint/config-loader/src/preset-loader.ts
  packages/@textlint/config-loader/test/index.test.ts
  packages/@textlint/config-loader/test/modules_fixtures/@scope/textlint-rule-a/index.js
  packages/@textlint/config-loader/test/modules_fixtures/@scope/textlint-rule-a/package.json
  packages/@textlint/config-loader/test/modules_fixtures/@scope/textlint-rule-b/index.js
  packages/@textlint/config-loader/test/modules_fixtures/@scope/textlint-rule-b/package.json
  packages/@textlint/config-loader/test/modules_fixtures/@scope/textlint-rule-c/index.js
  packages/@textlint/config-loader/test/modules_fixtures/@scope/textlint-rule-c/package.json
  packages/@textlint/config-loader/test/modules_fixtures/@scope/textlint-rule-preset-abc/index.js
  packages/@textlint/config-loader/test/modules_fixtures/@scope/textlint-rule-preset-abc/package.json
  packages/@textlint/config-loader/test/modules_fixtures/textlint-rule-c/index.js
  packages/@textlint/config-loader/test/modules_fixtures/textlint-rule-c/package.json
  packages/@textlint/config-loader/test/modules_fixtures/textlint-rule-preset-abc-but-unique-rule-key/index.js
  packages/@textlint/config-loader/test/modules_fixtures/textlint-rule-preset-abc-but-unique-rule-key/package.json
  packages/@textlint/config-loader/test/snapshots/disable-child-rule-of-preset/output.json
  packages/@textlint/config-loader/test/snapshots/no-used-rule-will-be-skip-to-load/output.json
  packages/@textlint/config-loader/test/snapshots/plguin/output.json
  packages/@textlint/config-loader/test/snapshots/ruke-key-should-refer-property-name/input.json
  packages/@textlint/config-loader/test/snapshots/ruke-key-should-refer-property-name/output.json
  packages/@textlint/config-loader/test/snapshots/scoped-rule/input.json
  packages/@textlint/config-loader/test/snapshots/scoped-rule/output.json
Labels: Type: Feature

#1089 fix: allow missing parameters for loadTextlintrc
  packages/textlint/src/loader/TextlintrcLoader.ts
  packages/textlint/test/loadTextlintrc/loadTextlintrc.test.ts
Labels: Type: Bug

#1092 fix(textlint): fix to print results when the `--dry-run` option is specified.
  packages/textlint/src/cli.ts
  packages/textlint/test/cli/cli-test.ts
Labels: Type: Bug
