Repository textlint/textlint, pull requests merged in 2023-07, with the labels that each got.

#1195 loadFixerFormatter is not use in example.
  docs/use-as-modules.md
Labels: Type: Documentation

#1198 chore: remove packages from lerna.json
  lerna.json
  package-lock.json
  package.json
  tsconfig.json
Labels: Type: Dependencies

#1201 refactor(textlint): move deprecated code to DEPRECATED/ dir
  package-lock.json
  packages/textlint/src/DEPRECATED/config.ts
  packages/textlint/src/DEPRECATED/config/config-loader.ts
  packages/textlint/src/DEPRECATED/config/config-util.ts
  packages/textlint/src/DEPRECATED/config/package-prefix.ts
  packages/textlint/src/DEPRECATED/config/plugin-loader.ts
  packages/textlint/src/DEPRECATED/config/preset-loader.ts
  packages/textlint/src/DEPRECATED/config/separate-by-config-option.ts
  packages/textlint/src/DEPRECATED/engine/textlint-engine-core.ts
  packages/textlint/src/DEPRECATED/engine/textlint-module-loader.ts
  packages/textlint/src/DEPRECATED/engine/textlint-module-mapper.ts
  packages/textlint/src/DEPRECATED/engine/textlint-module-resolver.ts
  packages/textlint/src/DEPRECATED/textfix-engine.ts
  packages/textlint/src/DEPRECATED/textlint-core.ts
  packages/textlint/src/DEPRECATED/textlint-engine.ts
  packages/textlint/src/DEPRECATED/textlint-package-name-util.ts
  packages/textlint/src/config/config-initializer.ts
  packages/textlint/src/index.ts
  packages/textlint/src/parallel/lint-worker-master.ts
  packages/textlint/src/parallel/lint-worker.ts
  packages/textlint/src/shared/README.md
  packages/textlint/src/shared/type/MessageType.ts
  packages/textlint/src/textlint.ts
  packages/textlint/src/util/find-util.ts
  packages/textlint/src/util/fs-promise.ts
  packages/textlint/src/util/traverse.ts
  packages/textlint/test/config-initializer/config-initializer-test.ts
  packages/textlint/test/config-loader/config-loader-test.ts
  packages/textlint/test/config/config-as-example-test.ts
  packages/textlint/test/config/config-test.ts
  packages/textlint/test/engine/textfix-engine-test.ts
  packages/textlint/test/engine/textlint-engine-test.ts
  packages/textlint/test/execute-file-backers/cache-backer-test.ts
  packages/textlint/test/plugin-loader/plugin-loader-test.ts
  packages/textlint/test/textlint-core-fixer/textlint-core-fixer-test.ts
  packages/textlint/test/textlint-module-mapper/textlint-module-mapper-test.ts
  packages/textlint/test/textlint-module-resolver/textlint-module-resolver-test.ts
  packages/textlint/test/textlint-package-name-util/textlint-package-name-util-test.ts
  packages/textlint/test/textlint/textlint-test.ts
Labels: Type: Refactoring

#1203 test: move kernel's test to kernel
  packages/@textlint/kernel/test/context/TextlintRuleContext-test.ts
  packages/@textlint/kernel/test/context/assert-rule-context.ts
  packages/textlint/test/rule-context/assert-rule-context.ts
  packages/textlint/test/rule-context/rule-context-fixer-test.ts
  packages/textlint/test/textlint/textlint-test.ts
Labels: Type: Testing
