Repository textlint/textlint, pull requests merged in 2024-01, with the labels that each got.

#1308 fix(kernel): remove unused TextlintConfigObject
  .github/workflows/ci.yml
  .node-version
  packages/@textlint/kernel/src/textlint-kernel-interface.ts
Labels: Type: Refactoring

#1319 chore!: move gulp-textlint to out of monorepo
  .github/workflows/ci.yml
  nx.json
  package-lock.json
  packages/@textlint/config-loader/src/TextlintConfigDescriptor.ts
  packages/@textlint/config-loader/src/textlint-module-resolver.ts
  packages/@textlint/config-loader/test/index.test.ts
  packages/@textlint/kernel/test/helper/ExamplePlugin.ts
  packages/gulp-textlint/.gitignore
  packages/gulp-textlint/.mocharc.json
  packages/gulp-textlint/README.md
  packages/gulp-textlint/example/.textlintrc
  packages/gulp-textlint/example/README.md
  packages/gulp-textlint/example/gulpfile.js
  packages/gulp-textlint/example/package.json
  packages/gulp-textlint/example/prh.yml
  packages/gulp-textlint/index.js
  packages/gulp-textlint/package.json
  packages/gulp-textlint/test/.textlintrc
  packages/gulp-textlint/test/fixtures/fail/1.md
  packages/gulp-textlint/test/fixtures/pass/1.md
  packages/gulp-textlint/test/prh.yml
  packages/gulp-textlint/test/test.js
Labels: Type: Breaking Change

#1322 fix(config-loader): enhance config-loader results
  packages/@textlint/config-loader/src/TextlintConfigDescriptor.ts
  packages/@textlint/config-loader/src/loader.ts
  packages/@textlint/config-loader/src/textlint-module-resolver.ts
  packages/@textlint/config-loader/test/snapshots/disable-child-rule-of-preset/output.json
  packages/@textlint/config-loader/test/snapshots/esm/output.json
  packages/@textlint/config-loader/test/snapshots/no-used-rule-will-be-skip-to-load/output.json
  packages/@textlint/config-loader/test/snapshots/plguin/output.json
  packages/@textlint/config-loader/test/snapshots/preset/output.json
  packages/@textlint/config-loader/test/snapshots/ruke-key-should-refer-property-name/output.json
  packages/@textlint/config-loader/test/snapshots/scoped-rule/output.json
  packages/@textlint/kernel/src/textlint-kernel-interface.ts
Labels: Type: Feature, Type: Breaking Change

#1272 Removes CLI from @textlint/linter-formatter
  packages/@textlint/linter-formatter/src/cli.ts
Labels: Type: Breaking Change

#1338 fix(textlint): remove `--parallel` and `--maxConcurrency` flag
  packages/textlint/src/options.ts
  packages/textlint/src/parallel/lint-worker-master.ts
  packages/textlint/src/parallel/lint-worker.ts
Labels: Type: Breaking Change
