Repository textlint/textlint, pull requests merged in 2024-08, with the labels that each got.

#1401 refactor(markdown-to-ast): migrate to `neotraverse`
  package-lock.json
  packages/@textlint/markdown-to-ast/package.json
  packages/@textlint/markdown-to-ast/src/index.ts
  packages/@textlint/markdown-to-ast/test/markdown-parser-test.ts
Labels: Type: Refactoring

#1407 fix(docs): remove Lato from the documentation website
  website/static/css/custom.css
  website/static/css/index.css
Labels: Type: Website

#1414 feat(textlint): Add `linter.scanFilePath` API
  .github/workflows/ci.yml
  docs/use-as-modules.md
  examples/use-as-module/index.mjs
  package-lock.json
  packages/textlint/package.json
  packages/textlint/src/DEPRECATED/engine/textlint-engine-core.ts
  packages/textlint/src/createLinter.ts
  packages/textlint/src/util/find-util.ts
  packages/textlint/src/util/old-find-util.ts
  packages/textlint/src/util/separate-by-availability.ts
  packages/textlint/test/cli/cli-test.ts
  packages/textlint/test/createLinter/createLinter.test.ts
  packages/textlint/test/createLinter/fixtures/.textlintignore
  packages/textlint/test/createLinter/fixtures/test-files/ignored.md
  packages/textlint/test/createLinter/fixtures/test-files/test.md
  packages/textlint/test/util/find-util-test.ts
  packages/textlint/test/util/fixtures/(find-util)/.textlintignore
  packages/textlint/test/util/fixtures/(find-util)/README.md
  packages/textlint/test/util/fixtures/(find-util)/dir/ignored.md
  packages/textlint/test/util/fixtures/(find-util)/dir/subdir/test.md
  packages/textlint/test/util/fixtures/(find-util)/dir/test.md
  packages/textlint/test/util/fixtures/(find-util)/ignored/subdir/test.md
  packages/textlint/test/util/fixtures/(find-util)/ignored/test.md
  packages/textlint/test/util/old-find-util-test.ts
  packages/textlint/test/util/separate-by-availability-test.ts
Labels: Type: Feature

#1417 feat(textlint-scripts): update to pkg-to-readme@3 and `textlint-scripts init --yes`
  package-lock.json
  packages/textlint-scripts/examples/example-dynamic-import/package.json
  packages/textlint-scripts/examples/example-ts/package.json
  packages/textlint-scripts/examples/example/README.md
  packages/textlint-scripts/examples/example/package.json
  packages/textlint-scripts/package.json
  packages/textlint-scripts/scripts/init.js
  packages/textlint-scripts/test/test-example.js
Labels: Type: Feature
