Repository textlint/textlint, pull requests merged in 2025-05, with the labels that each got.

#1497 feat(kernel): support multi-part extensions in plugin
  packages/@textlint/kernel/src/descriptor/TextlintPluginDescriptors.ts
  packages/@textlint/kernel/test/descriptor/TextlintPluginDescritors-test.ts
Labels: Type: Feature

#1499 feat(textlint): unify punctuation in CLI option descriptions
  packages/textlint/src/options.ts
Labels: Type: Documentation

#1511 refactor: replace get-stdin with built-in stream consumers
  package-lock.json
  packages/textlint/bin/textlint.js
  packages/textlint/package.json
Labels: Type: Refactoring

#1514 chore: remove unused clsx dependency
  package-lock.json
  website/package.json
Labels: Type: Refactoring
