Repository textlint/textlint, pull requests merged in 2025-08, with the labels that each got.

#1688 chore(deps): remove unused mkdirp dependency
  packages/textlint/package.json
  pnpm-lock.yaml
Labels: Type: Dependencies

#1698 fix(textlint-tester): support empty string test cases
  packages/textlint-tester/src/textlint-tester.ts
  packages/textlint-tester/test/textlint-tester.test.ts
Labels: Type: Bug

#1711 CI: fix actions
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-release-pr.yml
  .github/workflows/release-canary.yml
  .github/workflows/release.yml
  .github/workflows/website-preview.yml
  .github/workflows/website.yml
Labels: Type: CI

#1714 chore: add version comments to GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-release-pr.yml
  .github/workflows/release-canary.yml
  .github/workflows/release.yml
  .github/workflows/website-preview.yml
  .github/workflows/website.yml
Labels: Type: CI

#1720 refactor: format code
  docs/example/rules/example-rule.js
  examples/perf/perf.js
  examples/perf/run.js
  examples/rulesdir/rules/no-todo.js
  packages/@textlint/config-loader/src/is.ts
  packages/@textlint/config-loader/src/loader.ts
  packages/@textlint/config-loader/test/index.test.ts
  packages/@textlint/kernel/test/textlint-kernel.test.ts
  packages/@textlint/linter-formatter/src/formatters/pretty-error.ts
  packages/@textlint/linter-formatter/test/formatters/junit.test.ts
  packages/@textlint/linter-formatter/test/formatters/pretty-error.test.ts
  packages/@textlint/linter-formatter/test/test-helper.ts
  packages/@textlint/markdown-to-ast/test/markdown-parser.test.ts
  packages/@textlint/textlint-plugin-markdown/src/MarkdownProcessor.ts
  packages/@textlint/textlint-plugin-text/src/TextProcessor.ts
  packages/textlint/test/cli-snapshot-test/cli-snapshots.test.ts
  packages/textlint/test/cli/cli-exit-status-faq.test.ts
  packages/textlint/test/cli/cli-preset-severity.test.ts
  packages/textlint/test/cli/cli.test.ts
  packages/textlint/test/config-initializer/config-initializer.test.ts
  website/docusaurus.config.js
Labels: Type: Refactoring
