Repository textlint/textlint, pull requests merged in 2025-04, with the labels that each got.

#1474 fix: add type=commonjs
  packages/@textlint/ast-node-types/package.json
  packages/@textlint/ast-tester/package.json
  packages/@textlint/ast-traverse/package.json
  packages/@textlint/config-loader/package.json
  packages/@textlint/feature-flag/package.json
  packages/@textlint/fixer-formatter/package.json
  packages/@textlint/kernel/package.json
  packages/@textlint/legacy-textlint-core/package.json
  packages/@textlint/linter-formatter/package.json
  packages/@textlint/markdown-to-ast/package.json
  packages/@textlint/module-interop/package.json
  packages/@textlint/source-code-fixer/package.json
  packages/@textlint/text-to-ast/package.json
  packages/@textlint/textlint-plugin-markdown/package.json
  packages/@textlint/textlint-plugin-text/package.json
  packages/@textlint/types/package.json
  packages/@textlint/utils/package.json
  packages/textlint-scripts/package.json
  packages/textlint-tester/package.json
  packages/textlint/package.json
Labels: Type: Bug

#1472 feat(config-loader): validate UTF-8 encoding for configuration file
  packages/@textlint/config-loader/src/config-loader.ts
  packages/@textlint/config-loader/test/fixtures/euc-jp.json
  packages/@textlint/config-loader/test/fixtures/shift-jis.json
  packages/@textlint/config-loader/test/index.test.ts
Labels: Type: Feature

#1471 docs: correct `TxtCodeBlockNode` node type
  docs/txtnode.md
Labels: Type: Documentation

#1477 docs: replace vscode-textlint link
  README.md
Labels: Type: Documentation

#1483 fix(website): use `textlint.org` as domain
  website/siteConfig.js
Labels: Type: Website

#1484 fix(website): fix `CNAME` config
  website/siteConfig.js
Labels: Type: Website

#1485 fix(docs): update links from textlint.github.io to textlint.org
  .github/workflows/ci.yml
  README.md
  docs/rule-fixable.md
  docs/rule.md
  docs/txtnode.md
  examples/config-in-package-json/README.md
  packages/@textlint/kernel/src/textlint-kernel.ts
  packages/@textlint/legacy-textlint-core/README.md
  packages/@textlint/markdown-to-ast/README.md
  packages/@textlint/text-to-ast/README.md
  packages/textlint-scripts/README.md
  packages/textlint-tester/README.md
  packages/textlint/README.md
  packages/textlint/src/DEPRECATED/textfix-engine.ts
  packages/textlint/src/DEPRECATED/textlint-core.ts
  packages/textlint/src/DEPRECATED/textlint-engine.ts
  packages/textlint/src/index.ts
  packages/textlint/src/textlint.ts
  test/benchmark/README.md
  website/blog/2018-05-22-new-website.md
  website/blog/2018-07-22-textlint-11.md
  website/blog/2023-01-27-textlint-13.md
  website/blog/2024-02-03-textlint-14.md
  website/pages/en/index.js
Labels: Type: Documentation

#1490 chore(website): use new docsearch api key
  website/siteConfig.js
Labels: Type: Website

#1494 Update to Docusaurus v3
  .eslintignore
  .github/workflows/website.yml
  .gitignore
  docs/CONTRIBUTING.md
  docs/faq/failed-to-load-textlints-module.md
  docs/faq/line-column-or-index.md
  docs/plugin.md
  docs/rule-advanced.md
  docs/rule-tips-after-all.md
  docs/rule.md
  netlify.toml
  package-lock.json
  package.json
  packages/textlint-scripts/examples/example-ts/tsconfig.json
  website/.eslintrc.js
  website/CHANGELOG.md
  website/blog/2018-01-13-renewing-1.0.0.md
  website/blog/2018-05-22-new-website.md
  website/blog/2018-07-22-textlint-11.md
  website/blog/2021-05-24-textlint-12.md
  website/blog/2023-01-27-textlint-13.md
  website/blog/2024-02-03-textlint-14.md
  website/blog/assets/2018-05-22-new-website.png
  website/blog/authors.yml
  website/core/Footer.js
  website/docusaurus.config.js
  website/i18n/en.json
  website/package.json
  website/pages/en/help.js
  website/pages/en/index.js
  website/pages/en/users.js
  website/prh.yml
  website/siteConfig.js
  website/src/css/customTheme.css
  website/src/pages/help.jsx
  website/src/pages/index.jsx
  website/src/pages/index.module.css
  website/src/pages/users.jsx
  website/src/pages/users.module.css
Labels: Type: Website

#1495 docs: update description from 'text and markdown' to 'natural language'
  packages/textlint/README.md
  website/docusaurus.config.js
  website/src/pages/index.jsx
Labels: Type: Documentation
