Repository textlint/textlint, pull requests merged in 2025-07, with the labels that each got.

#1618 refactor(eslint): fix eslint warning
  docs/example/rules/example-rule.js
  eslint.config.js
  examples/perf/perf.js
  examples/perf/run.js
  examples/rulesdir/rules/no-todo.js
  examples/use-as-module/index.mjs
  packages/@textlint/ast-tester/src/index.ts
  packages/@textlint/ast-tester/src/unist-test.ts
  packages/@textlint/ast-traverse/src/index.ts
  packages/@textlint/config-loader/src/TextlintRcConfig.ts
  packages/@textlint/config-loader/src/is.ts
  packages/@textlint/config-loader/src/loader.ts
  packages/@textlint/config-loader/test/index.test.ts
  packages/@textlint/fixer-formatter/src/formatters/compats.ts
  packages/@textlint/fixer-formatter/src/formatters/diff.ts
  packages/@textlint/kernel/src/descriptor/rule-creator-helper.ts
  packages/@textlint/kernel/src/messages/filter-severity-process.ts
  packages/@textlint/kernel/src/task/promise-event-emitter.ts
  packages/@textlint/kernel/src/task/task-runner.ts
  packages/@textlint/kernel/src/task/textlint-core-task.ts
  packages/@textlint/kernel/src/util/timing.ts
  packages/@textlint/kernel/test/context/TextlintLocator/TextlintLocator.test.ts
  packages/@textlint/kernel/test/context/TextlintRuleError.test.ts
  packages/@textlint/kernel/test/descriptor/TextlintRulesDescriptor.test.ts
  packages/@textlint/kernel/test/helper/AsyncPlugin.ts
  packages/@textlint/kernel/test/helper/BinaryPlugin.ts
  packages/@textlint/kernel/test/helper/ExamplePlugin.ts
  packages/@textlint/linter-formatter/src/formatters/table.ts
  packages/@textlint/linter-formatter/test/formatters/junit.test.ts
  packages/@textlint/linter-formatter/test/formatters/pretty-error.test.ts
  packages/@textlint/markdown-to-ast/debug-broken-auto-link.mts
  packages/@textlint/markdown-to-ast/src/parse-markdown.ts
  packages/@textlint/markdown-to-ast/test/compliance-tests.ts
  packages/@textlint/markdown-to-ast/test/markdown-parser.test.ts
  packages/@textlint/markdown-to-ast/test/parsing.test.ts
  packages/@textlint/text-to-ast/test/compliance.test.ts
  packages/@textlint/text-to-ast/test/snapshot.test.ts
  packages/@textlint/types/src/Plugin/TextlintPluginModule.ts
  packages/@textlint/types/src/Rule/TextlintFilterRuleContext.ts
  packages/@textlint/types/src/Rule/TextlintRuleModule.ts
  packages/@textlint/types/src/Rule/TextlintRuleOptions.ts
  packages/textlint-scripts/examples/example-ts/.gitignore
  packages/textlint-scripts/examples/example-ts/tsconfig.json
  packages/textlint-tester/src/textlint-tester.ts
  packages/textlint/src/engine/processor-map.ts
  packages/textlint/src/engine/rule-map.ts
  packages/textlint/test/cli-snapshot-test/cli-snapshots.test.ts
  packages/textlint/test/cli/cli-exit-status-faq.test.ts
  packages/textlint/test/cli/cli-preset-severity.test.ts
  packages/textlint/test/cli/cli.test.ts
  tsconfig.json
Labels: Type: Refactoring

#1623 fix(mcp): allow additional properties in TextlintMessage schema
  packages/textlint/src/mcp/server.ts
  packages/textlint/test/mcp/fixtures/invalid.md
  packages/textlint/test/mcp/server.test.ts
Labels: Type: Bug

#1630 refactor(mcp): improve test structure and add configuration options
  .github/workflows/ci.yml
  eslint.config.js
  packages/textlint/src/mcp/schemas.ts
  packages/textlint/src/mcp/server.ts
  packages/textlint/test/mcp-snapshot-test/mcp-snapshots.test.ts
  packages/textlint/test/mcp-snapshot-test/snapshot-utils.ts
  packages/textlint/test/mcp-snapshot-test/snapshots/basic-lint-file/input.ts
  packages/textlint/test/mcp-snapshot-test/snapshots/basic-lint-file/output.json
  packages/textlint/test/mcp-snapshot-test/snapshots/basic-lint-file/test-file.md
  packages/textlint/test/mcp-snapshot-test/snapshots/custom-rule-todo/input.ts
  packages/textlint/test/mcp-snapshot-test/snapshots/custom-rule-todo/output.json
  packages/textlint/test/mcp-snapshot-test/snapshots/custom-rule-todo/textlintrc.json
  packages/textlint/test/mcp-snapshot-test/snapshots/custom-rule-todo/todo-file.md
  packages/textlint/test/mcp-snapshot-test/snapshots/error-unsupported-extension/input.ts
  packages/textlint/test/mcp-snapshot-test/snapshots/error-unsupported-extension/output.json
  packages/textlint/test/mcp-snapshot-test/snapshots/lint-text-basic/input.ts
  packages/textlint/test/mcp-snapshot-test/snapshots/lint-text-basic/output.json
  packages/textlint/test/mcp-snapshot-test/types.ts
  packages/textlint/test/mcp/fixtures/configs/minimal-config.json
  packages/textlint/test/mcp/fixtures/configs/strict-config.json
  packages/textlint/test/mcp/fixtures/configs/with-custom-rule.json
  packages/textlint/test/mcp/fixtures/configs/with-preset.json
  packages/textlint/test/mcp/fixtures/empty.md
  packages/textlint/test/mcp/fixtures/large-file.md
  packages/textlint/test/mcp/fixtures/lint-errors.md
  packages/textlint/test/mcp/fixtures/rule_modules/@textlint/textlint-plugin-markdown/index.js
  packages/textlint/test/mcp/fixtures/rule_modules/@textlint/textlint-plugin-markdown/package.json
  packages/textlint/test/mcp/fixtures/rule_modules/@textlint/textlint-plugin-text/index.js
  packages/textlint/test/mcp/fixtures/rule_modules/@textlint/textlint-plugin-text/package.json
  packages/textlint/test/mcp/fixtures/rule_modules/textlint-rule-preset-test/index.js
  packages/textlint/test/mcp/fixtures/rule_modules/textlint-rule-preset-test/package.json
  packages/textlint/test/mcp/fixtures/rule_modules/textlint-rule-test-rule/index.js
  packages/textlint/test/mcp/fixtures/rule_modules/textlint-rule-test-rule/package.json
  packages/textlint/test/mcp/fixtures/unsupported.xyz
  packages/textlint/test/mcp/fixtures/with-exclamation.md
  packages/textlint/test/mcp/fixtures/with-todo.md
  packages/textlint/test/mcp/server.test.ts
Labels: Type: Testing

#1633 test(mcp): add comprehensive tests for createStructuredErrorResponse
  packages/textlint/src/mcp/server.ts
  packages/textlint/test/mcp-snapshot-test/snapshots/error-empty-stdin-filename/input.ts
  packages/textlint/test/mcp-snapshot-test/snapshots/error-empty-stdin-filename/output.json
  packages/textlint/test/mcp-snapshot-test/snapshots/error-file-not-found/input.ts
  packages/textlint/test/mcp-snapshot-test/snapshots/error-file-not-found/output.json
  packages/textlint/test/mcp-snapshot-test/snapshots/error-fix-file-not-found/input.ts
  packages/textlint/test/mcp-snapshot-test/snapshots/error-fix-file-not-found/output.json
  packages/textlint/test/mcp-snapshot-test/snapshots/error-fix-text-empty-filename/input.ts
  packages/textlint/test/mcp-snapshot-test/snapshots/error-fix-text-empty-filename/output.json
Labels: Type: Testing

#1634 feat(mcp): support CLI flags with --mcp option
  docs/mcp.md
  packages/textlint/src/cli.ts
  packages/textlint/src/mcp/server.ts
  packages/textlint/test/mcp/server.test.ts
Labels: Type: Feature

#1636 feat(mcp): add debug logging support for MCP server
  packages/textlint/src/cli.ts
  packages/textlint/src/mcp/server.ts
Labels: Type: Enhance

#1652 docs: add Claude Code setup instructions to MCP documentation
  docs/mcp.md
Labels: Type: Documentation

#1663 fix(kernel): add browser compatibility for timing utility
  packages/@textlint/kernel/src/util/timing.ts
Labels: Type: Bug

#1668 docs: add filterRules parameter to TextlintKernelDescriptor
  docs/use-as-modules.md
Labels: Type: Documentation

#1669 feat(website): make the entire sidebar hideable
  website/docusaurus.config.js
Labels: Type: Website

#1671 docs: add GitHub Actions CI/CD integration examples
  docs/integrations.md
Labels: Type: Documentation
