Repository textlint/textlint, pull requests merged in 2025-06, with the labels that each got.

#1522 feat(textlint): add `--mcp` option
  README.md
  docs/cli.md
  package-lock.json
  packages/textlint/package.json
  packages/textlint/src/DEPRECATED/config.ts
  packages/textlint/src/cli.ts
  packages/textlint/src/mcp/server.ts
  packages/textlint/src/options.ts
  packages/textlint/test/cli/cli-test.ts
  packages/textlint/test/mcp/fixtures/ok.md
  packages/textlint/test/mcp/server.test.ts
Labels: Type: Feature

#1525 docs: add mcp
  website/sidebars.json
Labels: Type: Website

#1526 docs(mcp): add configuration prerequisite and improve setup instructions
  docs/mcp.md
Labels: Type: Documentation

#1529 refactor: use for..of instead of traditional for loop
  packages/@textlint/config-loader/src/textlint-package-name-util.ts
  packages/@textlint/utils/src/KeyPath/KeyPathUtil.ts
Labels: Type: Refactoring

#1548 Add pnpm installation step to release job
  .github/workflows/create-release-pr.yml
  .github/workflows/release.yml
Labels: Type: CI

#1572 refactor(textlint): use "read-package-up"
  netlify.toml
  packages/textlint/package.json
  packages/textlint/src/DEPRECATED/config.ts
  packages/textlint/src/cli.ts
  packages/textlint/src/config/config-initializer.ts
  packages/textlint/src/createLinter.ts
  packages/textlint/src/mcp/server.ts
  packages/textlint/test/mcp/server.test.ts
  pnpm-lock.yaml
Labels: Type: Breaking Change, Type: Refactoring

#1575 refactor: rename: change test files from -test.ts to .test.ts
  examples/use-as-ts-module/tsconfig.json
  packages/@textlint/ast-node-types/test/TextLintASTNodeTypes.test.ts
  packages/@textlint/ast-tester/test/textlint-ast-tester.test.ts
  packages/@textlint/ast-traverse/test/txt-traverse.test.ts
  packages/@textlint/feature-flag/test/textlint-feature-flag.test.ts
  packages/@textlint/fixer-formatter/test/textlint-fixer-formatter.test.ts
  packages/@textlint/kernel/test/context/TextlintLocator/TextlintLocator.test.ts
  packages/@textlint/kernel/test/context/TextlintRuleContext.test.ts
  packages/@textlint/kernel/test/context/TextlintRuleError.test.ts
  packages/@textlint/kernel/test/context/TextlintSourceCode/TextlintSourceCode.test.ts
  packages/@textlint/kernel/test/descriptor/TextlintKernelDescriptor.test.ts
  packages/@textlint/kernel/test/descriptor/TextlintPluginDescritors.test.ts
  packages/@textlint/kernel/test/descriptor/TextlintRulesDescriptor.test.ts
  packages/@textlint/kernel/test/descriptor/rule-creator-helper/rule-creator-helper.test.ts
  packages/@textlint/kernel/test/kernel-plugin.test.ts
  packages/@textlint/kernel/test/messages/filter-duplicated-process.test.ts
  packages/@textlint/kernel/test/messages/filter-ignored-process.test.ts
  packages/@textlint/kernel/test/messages/sort-messages-process.test.ts
  packages/@textlint/kernel/test/rule-fixer/rule-fixer.test.ts
  packages/@textlint/kernel/test/source-code-fixer/source-code-fixer.test.ts
  packages/@textlint/kernel/test/source-location/source-location.test.ts
  packages/@textlint/kernel/test/textlint-kernel-snapshots.test.ts
  packages/@textlint/kernel/test/textlint-kernel.test.ts
  packages/@textlint/linter-formatter/test/textlint-formatter.test.ts
  packages/@textlint/markdown-to-ast/test/markdown-parser.test.ts
  packages/@textlint/markdown-to-ast/test/parsing.test.ts
  packages/@textlint/text-to-ast/test/compliance.test.ts
  packages/@textlint/text-to-ast/test/plaintext-parser.test.ts
  packages/@textlint/text-to-ast/test/snapshot.test.ts
  packages/@textlint/textlint-plugin-markdown/test/MarkdownProcessor.test.ts
  packages/@textlint/textlint-plugin-text/test/TextProcessor.test.ts
  packages/@textlint/types/test/Rule/TextlintRuleModule.test.ts
  packages/@textlint/types/test/Rule/TxtNode.test.ts
  packages/@textlint/utils/test/KeyPath/config-key-normalizer.test.ts
  packages/textlint-scripts/examples/example-ts/test/index.test.ts
  packages/textlint-tester/test/async.test.ts
  packages/textlint-tester/test/textlint-tester-fixer.test.ts
  packages/textlint-tester/test/textlint-tester-invalid-testcofig.test.ts
  packages/textlint-tester/test/textlint-tester.test.ts
  packages/textlint/test/cli/cli.test.ts
  packages/textlint/test/config-initializer/config-initializer.test.ts
  packages/textlint/test/engine/rule-loader.test.ts
  packages/textlint/test/execute-file-backers/cache-backer.test.ts
  packages/textlint/test/object-to-kernel-format/object-to-kernel-format.test.ts
  packages/textlint/test/other/parsing.test.ts
  packages/textlint/test/pluguins/PluginOption.test.ts
  packages/textlint/test/rule-context/rule-context.test.ts
  packages/textlint/test/rule-tips/rule-tips-after-all.test.ts
  packages/textlint/test/textlint-core/async-rule.test.ts
  packages/textlint/test/util/find-util.test.ts
  packages/textlint/test/util/old-find-util.test.ts
  packages/textlint/test/util/separate-by-availability.test.ts
  scripts/rename-test-files.js
  vitest.config.mts
Labels: Type: Refactoring

#1576 refactor(test): remove unused import from test file
  packages/@textlint/ast-tester/test/textlint-ast-tester.test.ts
Labels: Type: Refactoring

#1578 feat: remove deprecated createFormatter function
  packages/@textlint/fixer-formatter/src/index.ts
  packages/@textlint/linter-formatter/README.md
  packages/@textlint/linter-formatter/src/index.ts
  packages/@textlint/linter-formatter/test/textlint-formatter.test.ts
  website/blog/2025-06-22-textlint-15-draft.md
Labels: Type: Breaking Change, Type: Refactoring

#1583 fix: Make lintFiles respect ignore patterns for absolute file paths (#1412)
  docs/cli.md
  docs/faq/exit-status.md
  examples/cli/package.json
  packages/textlint/src/cli.ts
  packages/textlint/src/createLinter.ts
  packages/textlint/src/util/find-util.ts
  packages/textlint/src/util/old-find-util.ts
  packages/textlint/test/cli/cli-exit-status-faq.test.ts
  packages/textlint/test/cli/cli.test.ts
  packages/textlint/test/createLinter/createLinter.test.ts
  packages/textlint/test/createLinter/fixtures/test-files/ignored.md
  packages/textlint/test/createLinter/fixtures/test-files/test.md
  packages/textlint/test/util/old-find-util.test.ts
  website/blog/2025-06-22-textlint-15-draft.md
Labels: Type: Breaking Change

#1588 fix: Remove 'module' field from packages with type=commonjs to fix webpack compatibility
  packages/@textlint/ast-node-types/package.json
  packages/@textlint/ast-node-types/tsconfig.module.json
  packages/@textlint/ast-tester/package.json
  packages/@textlint/ast-tester/tsconfig.module.json
  packages/@textlint/ast-traverse/package.json
  packages/@textlint/ast-traverse/tsconfig.module.json
  packages/@textlint/config-loader/package.json
  packages/@textlint/config-loader/tsconfig.module.json
  packages/@textlint/feature-flag/package.json
  packages/@textlint/feature-flag/tsconfig.module.json
  packages/@textlint/fixer-formatter/package.json
  packages/@textlint/fixer-formatter/tsconfig.module.json
  packages/@textlint/kernel/package.json
  packages/@textlint/kernel/tsconfig.module.json
  packages/@textlint/linter-formatter/package.json
  packages/@textlint/linter-formatter/tsconfig.module.json
  packages/@textlint/markdown-to-ast/package.json
  packages/@textlint/markdown-to-ast/tsconfig.module.json
  packages/@textlint/module-interop/package.json
  packages/@textlint/module-interop/tsconfig.module.json
  packages/@textlint/resolver/package.json
  packages/@textlint/resolver/tsconfig.module.json
  packages/@textlint/source-code-fixer/package.json
  packages/@textlint/source-code-fixer/tsconfig.module.json
  packages/@textlint/text-to-ast/package.json
  packages/@textlint/text-to-ast/tsconfig.module.json
  packages/@textlint/textlint-plugin-markdown/package.json
  packages/@textlint/textlint-plugin-markdown/tsconfig.module.json
  packages/@textlint/textlint-plugin-text/package.json
  packages/@textlint/textlint-plugin-text/tsconfig.module.json
  packages/@textlint/utils/package.json
  packages/@textlint/utils/tsconfig.module.json
Labels: Type: Bug

#1590 chore: fix clean script
  packages/@textlint/resolver/package.json
  packages/textlint/package.json
Labels: Type: Refactoring

#1599 chore: update globals from v15 to v16
  package.json
  pnpm-lock.yaml
Labels: dependencies

#1604 chore: fix typos
  docs/migration-to-v15.md
  docs/rule.md
  examples/perf/md/creation.md
  examples/perf/md/delete.md
  examples/perf/md/properties.md
  packages/textlint-tester/README.md
  packages/textlint-tester/test/textlint-tester-invalid-testcofig.test.ts
  packages/textlint/src/engine/execute-file-backers/README.md
  packages/textlint/test/config-initializer/config-initializer.test.ts
  packages/textlint/test/pluguins/PluginOption.test.ts
  packages/textlint/test/rule-context/rule-context.test.ts
  website/blog/2018-05-22-new-website.md
  website/blog/2018-07-22-textlint-11.md
  website/blog/2024-02-03-textlint-14.md
Labels: Type: Documentation

#1609 test(config-loader): add user config is `true` case
  packages/@textlint/config-loader/test/modules_fixtures/textlint-rule-preset-abc-with-severity/index.js
  packages/@textlint/config-loader/test/snapshots/preset-severity-preservation/input.json
  packages/@textlint/config-loader/test/snapshots/preset-severity-preservation/output.json
Labels: Type: Testing

#1612 CI(website-preview): fix checkout condition
  .github/workflows/website-preview.yml
Labels: Type: CI
