Repository textlint/textlint, pull requests merged in 2025-03, with the labels that each got.

#1461 Replace `--dryRun` with `--dry-run`
  docs/cli.md
  packages/textlint/bin/textlint.js
Labels: Type: Documentation

#1459 feat(@textlint/ast-node-types): add missing `LinkReference`, `ImageReference` and `Definition` node types
  docs/txtnode.md
  packages/@textlint/ast-node-types/src/ASTNodeTypes.ts
  packages/@textlint/ast-node-types/src/NodeType.ts
  packages/@textlint/ast-node-types/src/TypeofTxtNode.ts
  packages/@textlint/ast-node-types/src/index.ts
  packages/@textlint/types/test/Rule/TxtNode-test.ts
Labels: Type: Feature

#1466 docs: add note about `LinkReference`, `ImageReference` and `Definition`
  docs/txtnode.md
Labels: Type: Documentation

#1467 CI: pin actions's version
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-release-pr.yml
  .github/workflows/release-canary.yml
  .github/workflows/release.yml
  .github/workflows/website.yml
Labels: dependencies
